# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     service: backend-user
#   name: backend-user
# spec:
#   selector:
#     matchLabels:
#       service: backend-user
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         service: backend-user
#     spec:
#       containers:
#         - image: nouran96/udagram-api-user:v2
#           name: backend-user
#           imagePullPolicy: Always
#           resources:
#             requests:
#               memory: "1000Mi"
#               cpu: "250m"
#             limits:
#               memory: "2000Mi"
#               cpu: "500m"
#           env:
#             - name: URL
#               valueFrom:
#                 configMapKeyRef:
#                   name: udagram-configmap
#                   key: URL
#             - name: AWS_BUCKET
#               valueFrom:
#                 configMapKeyRef:
#                   name: udagram-configmap
#                   key: AWS_BUCKET
#             - name: AWS_PROFILE
#               valueFrom:
#                 configMapKeyRef:
#                   name: udagram-configmap
#                   key: AWS_PROFILE
#             - name: AWS_REGION
#               valueFrom:
#                 configMapKeyRef:
#                   name: udagram-configmap
#                   key: AWS_REGION
#             - name: JWT_SECRET
#               valueFrom:
#                 configMapKeyRef:
#                   name: udagram-configmap
#                   key: JWT_SECRET
#             - name: POSTGRES_DB
#               valueFrom:
#                 configMapKeyRef:
#                   name: udagram-configmap
#                   key: POSTGRES_DB
#             - name: POSTGRES_HOST
#               valueFrom:
#                 configMapKeyRef:
#                   name: udagram-configmap
#                   key: POSTGRES_HOST
#             - name: POSTGRES_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: udagram-secret
#                   key: POSTGRES_PASSWORD
#             - name: POSTGRES_USERNAME
#               valueFrom:
#                 secretKeyRef:
#                   name: udagram-secret
#                   key: POSTGRES_USERNAME
#           ports:
#             - containerPort: 8080
#           volumeMounts:
#             - name: aws-secret
#               mountPath: "/root/.aws/"
#               readOnly: true
#       restartPolicy: Always
#       volumes:
#         - name: aws-secret
#           secret:
#             secretName: udagram-aws-secret
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - image: nouran96/udagram-api-user:v2
        name: backend-user
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: udagram-configmap
        - secretRef:
            name: udagram-secret
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true        
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: udagram-aws-secret