# apiVersion: v1
# kind: Service
# metadata:
#   name: udagram-frontend
#   labels:
#     run: udagram-frontend
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#   selector:
#     run: udagram-frontend
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - name: "8100"
      port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: frontend
  type: ClusterIP
status:
  loadBalancer: {}